export default {
    resolution: 1,
    visibleArea: 900,
    moveSpeed: 30,
    border: 50,
    importList: [
        {name: "mainBack", dir: "assets/spawn.png"},
        {name: "pepeBack", dir: "assets/pepehosting.png"},
        {name: "pepeBackSlap", dir: "assets/pepehostingSlap.png"},
        {name: "wcBack", dir: "assets/wc.png"},
        {name: "classroomBack", dir: "assets/classroomBack2.jpg"},
        {name: "beachBack", dir: "assets/beachBack.jpg"},
        {name: "padoruBlue", dir: "assets/padoru1.png"},
        {name: "padoruOriginalLeft", dir: "assets/padoruOriginalLeft.png"},
        {name: "padoruOriginalRight", dir: "assets/padoruOriginalRight.png"},
        {name: "padoruOriginalFront", dir: "assets/padoruOriginalFront.png"},
        {name: "padoruOriginalBack", dir: "assets/padoruOriginalBack.png"},
        {name: "presentThrow1", dir: "assets/presentThrow1.png"},
        {name: "presentThrow2", dir: "assets/presentThrow2.png"},
        {name: "presentThrow3", dir: "assets/presentThrow3.png"},
        {name: "presentThrow4", dir: "assets/presentThrow4.png"},
        {name: "present", dir: "assets/present.png"},
        {name: "pepeSign", dir: "assets/signPepe.png"},
        {name: "spawnSign", dir: "assets/signSpawn.png"},
        {name: "classSign", dir: "assets/signClass.png"},
        {name: "beachSign", dir: "assets/signBeach.png"},
        {name: "lever", dir: "assets/lever.png"},
        {name: "door", dir: "assets/pepehostingDoor.png"},
        {name: "wcDoor", dir: "assets/wcDoor.png"},
        {name: "aqua1", dir: "assets/aqua1.png"},
        {name: "aqua2", dir: "assets/aqua2.png"},
        {name: "aqua3", dir: "assets/aqua3.png"},
        {name: "aquaDance1", dir: "assets/aquaDance1.png"},
        {name: "aquaDance2", dir: "assets/aquaDance2.png"},
        {name: "aquaDance3", dir: "assets/aquaDance3.png"},
        {name: "aquaDance4", dir: "assets/aquaDance4.png"},
        {name: "kanna", dir: "assets/kanna.png"},
    ]
}