export default {
    resolution: 1,
    visibleArea: 900,
    moveSpeed: 30,
    border: 50,
    importList: [
        {name: "mainBack", dir: "assets/spawn.png"},
        {name: "pepeBack", dir: "assets/pepehosting.png"},
        {name: "pepeBackSlap", dir: "assets/pepehostingSlap.png"},
        {name: "wcBack", dir: "assets/wc.png"},
        {name: "classroomBack", dir: "assets/classroomBack2.jpg"},
        {name: "beachBack", dir: "assets/beachBack.jpg"},
        {name: "padoruOriginalLeft", dir: "assets/padoru/padoruOriginalLeft.png"},
        {name: "padoruOriginalRight", dir: "assets/padoru/padoruOriginalRight.png"},
        {name: "padoruOriginalFront", dir: "assets/padoru/padoruOriginalFront.png"},
        {name: "padoruOriginalBack", dir: "assets/padoru/padoruOriginalBack.png"},
        {name: "presentThrow1", dir: "assets/presentThrow1.png"},
        {name: "presentThrow2", dir: "assets/presentThrow2.png"},
        {name: "presentThrow3", dir: "assets/presentThrow3.png"},
        {name: "presentThrow4", dir: "assets/presentThrow4.png"},
        {name: "present", dir: "assets/present.png"},
        {name: "pepeSign", dir: "assets/signPepe.png"},
        {name: "spawnSign", dir: "assets/signSpawn.png"},
        {name: "classSign", dir: "assets/signClass.png"},
        {name: "beachSign", dir: "assets/signBeach.png"},
        {name: "lever", dir: "assets/lever.png"},
        {name: "door", dir: "assets/pepehostingDoor.png"},
        {name: "wcDoor", dir: "assets/wcDoor.png"},
        {name: "aqua1", dir: "assets/aqua1.png"},
        {name: "aqua2", dir: "assets/aqua2.png"},
        {name: "aqua3", dir: "assets/aqua3.png"},
        {name: "aquaDance1", dir: "assets/aquaDance1.png"},
        {name: "aquaDance2", dir: "assets/aquaDance2.png"},
        {name: "aquaDance3", dir: "assets/aquaDance3.png"},
        {name: "aquaDance4", dir: "assets/aquaDance4.png"},
        {name: "kanna", dir: "assets/kanna.png"},
        {name: "kurome1", dir: "assets/kurome/kurome1.png"},
        {name: "kurome2", dir: "assets/kurome/kurome2.png"},
        {name: "kurome3", dir: "assets/kurome/kurome3.png"},
        {name: "kurome4", dir: "assets/kurome/kurome4.png"},
        {name: "kurome5", dir: "assets/kurome/kurome5.png"},
        {name: "kurome6", dir: "assets/kurome/kurome6.png"},
        {name: "kurome7", dir: "assets/kurome/kurome7.png"},
        {name: "kurome8", dir: "assets/kurome/kurome8.png"},
        {name: "padoruMegumin", dir: "assets/padoru/padoruMegumin.png"},
        {name: "padoru1", dir: "assets/padoru/padoru1.png"},
        {name: "padoru2", dir: "assets/padoru/padoru2.png"},
        {name: "padoru3", dir: "assets/padoru/padoru3.png"},
        {name: "padoru4", dir: "assets/padoru/padoru4.png"},
        {name: "padoru5", dir: "assets/padoru/padoru5.png"},
        {name: "padoru6", dir: "assets/padoru/padoru6.png"},
        {name: "padoru7", dir: "assets/padoru/padoru7.png"},
        {name: "padoru9", dir: "assets/padoru/padoru9.png"},
        {name: "padoru10", dir: "assets/padoru/padoru10.png"},
        {name: "padoru11", dir: "assets/padoru/padoru11.png"},
        {name: "padoru12", dir: "assets/padoru/padoru12.png"}
    ]
}